version: '2'
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: mydb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbpassword

   web:
     depends_on:
       - db
     image: tomcat:8-jre8
     links: 
       - db
     restart: always
     volumes:
       - ./AdressService.war:/usr/local/tomcat/webapps/AdressService.war
       - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

volumes:
    db_data:
